import "@/app/globals.css";
import NextUiContext from "@/components/context/NextUiContext";
import Header from "@/components/dashboardComp/Header";
import Sidebar from "@/components/dashboardComp/Sidebar";
import { Roboto } from "next/font/google";

const roboto = Roboto({ 
    weight: ["100", "300", "400", "500", "700", "900"],
    subsets: ["latin"] 
  });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextUiContext>
          <div className="flex min-h-screen w-full flex-col bg-muted/40">
            <Sidebar/>
            <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
              <Header/>
              {children}
            </div>
          </div>
        </NextUiContext>
      </body>
    </html>
  );
}
