import "@/app/globals.css";
import Container from "@/components/common/Container";
import NextUiContext from "@/components/context/NextUiContext";
import Footer from "@/components/footer/primary/Footer";
import ScndFooter from "@/components/footer/secondry/ScndFooter";
import Header from "@/components/header/Header";
import { Roboto } from "next/font/google";

const roboto = Roboto({ 
    weight: ["100", "300", "400", "500", "700", "900"],
    subsets: ["latin"] 
  });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        <Container>
          <NextUiContext>
            {children}
          </NextUiContext>
        </Container>
        <Footer/>
        <ScndFooter/>
      </body>
    </html>
  );
}
